"""make schedule_rules times nullable

Revision ID: 7d508dadf6d0
Revises: 41a1f42164f7
Create Date: 2026-09-21 23:38:23.814009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d508dadf6d0'
down_revision: Union[str, None] = '41a1f42164f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_rules', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('schedule_rules', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_rules', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('schedule_rules', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
